[package]
name = "fuse_mt"
version = "0.4.4"
authors = ["William R. Fraser <wfraser@codewise.org>"]
repository = "https://github.com/wfraser/fuse-mt"
description = "A higher-level FUSE filesystem library with multi-threading and inode->path translation."
categories = ["filesystem"]
keywords = ["fuse", "filesystem"]
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
fuse = "0.3.1"
futures = "0.1"
libc = "0.2"
log = "0.4"
threadpool = "1.0"
time = "0.1"
tokio-core = "0.1"

[workspace]
members = [".", "example"]
